// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ScheduleAnywhere.Infrastructure.Data;

#nullable disable

namespace ScheduleAnywhere.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ScheduleAnywhere.Core.Domain.CoverageWatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_i");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("active_b");

                    b.Property<DateTime>("LastModifiedDateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("lastmodifieddatetime_dt");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name_nvc");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("int")
                        .HasColumnName("schedule_id_i");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleId");

                    b.ToTable("t_coverageWatch", (string)null);
                });

            modelBuilder.Entity("ScheduleAnywhere.Core.Domain.CoverageWatchDepartment", b =>
                {
                    b.Property<int>("CoverageWatchId")
                        .HasColumnType("int")
                        .HasColumnName("coveragewatch_id_i");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int")
                        .HasColumnName("department_id_i");

                    b.HasKey("CoverageWatchId", "DepartmentId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("t_mapCoverageWatchDepartment", (string)null);
                });

            modelBuilder.Entity("ScheduleAnywhere.Core.Domain.CoverageWatchPosition", b =>
                {
                    b.Property<int>("CoverageWatchId")
                        .HasColumnType("int")
                        .HasColumnName("coveragewatch_id_i");

                    b.Property<int>("PositionId")
                        .HasColumnType("int")
                        .HasColumnName("position_id_i");

                    b.HasKey("CoverageWatchId", "PositionId");

                    b.HasIndex("PositionId");

                    b.ToTable("t_mapCoverageWatchPosition", (string)null);
                });

            modelBuilder.Entity("ScheduleAnywhere.Core.Domain.CoverageWatchShift", b =>
                {
                    b.Property<int>("CoverageWatchId")
                        .HasColumnType("int")
                        .HasColumnName("coveragewatch_id_i");

                    b.Property<int>("ShiftId")
                        .HasColumnType("int")
                        .HasColumnName("shift_id_i");

                    b.HasKey("CoverageWatchId", "ShiftId");

                    b.HasIndex("ShiftId");

                    b.ToTable("t_mapCoverageWatchShift", (string)null);
                });

            modelBuilder.Entity("ScheduleAnywhere.Core.Domain.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_i");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("active_b");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description_nvc");

                    b.Property<DateTime>("LastModifiedDateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("lastmodifieddatetime_dt");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name_nvc");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_id_i");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("t_department", (string)null);
                });

            modelBuilder.Entity("ScheduleAnywhere.Core.Domain.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_i");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("active_b");

                    b.Property<bool>("CanLogin")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("canlogin_b");

                    b.Property<string>("Comments")
                        .HasColumnType("longtext")
                        .HasColumnName("comments_nvc");

                    b.Property<decimal?>("Cost")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("cost_sm");

                    b.Property<int?>("CostType")
                        .HasColumnType("int")
                        .HasColumnName("costtype_i");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_dt");

                    b.Property<DateTime?>("Deactivated")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deactivated_dt");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int")
                        .HasColumnName("department_id_i");

                    b.Property<string>("Email1")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email1_nvc");

                    b.Property<string>("Email2")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email2_nvc");

                    b.Property<string>("ExportIdentifier")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("exportidentifier_nvc");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("firstname_nvc");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("hiredate_dt");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("lastlogin_dt");

                    b.Property<DateTime>("LastModifiedDateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("lastmodifieddatetime_dt");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("lastname_nvc");

                    b.Property<int>("LocationId")
                        .HasColumnType("int")
                        .HasColumnName("location_id_i");

                    b.Property<string>("LoginToken")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("logintoken_nvc");

                    b.Property<string>("Mobile")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("mobile_nvc");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_id_i");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("password_nvc");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("password_salt_nvc");

                    b.Property<string>("Phone1")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("phone1_nvc");

                    b.Property<int>("PositionId")
                        .HasColumnType("int")
                        .HasColumnName("position_id_i");

                    b.Property<string>("ResetPasswordToken")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("resetpasswordtoken_nvc");

                    b.Property<string>("Ssn")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("ssn_nvc");

                    b.Property<int?>("SupervisorEmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("supervisor_employee_id_i");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("username_nvc");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("LocationId");

                    b.HasIndex("PositionId");

                    b.HasIndex("SupervisorEmployeeId");

                    b.HasIndex("OrganizationId", "Username")
                        .IsUnique();

                    b.ToTable("t_employee", (string)null);
                });

            modelBuilder.Entity("ScheduleAnywhere.Core.Domain.EmployeeRole", b =>
                {
                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("employee_id_i");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id_i");

                    b.HasKey("EmployeeId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("t_mapRoleEmployee", (string)null);
                });

            modelBuilder.Entity("ScheduleAnywhere.Core.Domain.EmployeeScheduleAccess", b =>
                {
                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("employee_id_i");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("int")
                        .HasColumnName("schedule_id_i");

                    b.HasKey("EmployeeId", "ScheduleId");

                    b.HasIndex("ScheduleId");

                    b.ToTable("t_mapScheduleEmployeeAccess", (string)null);
                });

            modelBuilder.Entity("ScheduleAnywhere.Core.Domain.Explanation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_i");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("abbreviation_nvc");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("active_b");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description_nvc");

                    b.Property<bool>("IsTimeOff")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("istimeoff_b");

                    b.Property<DateTime>("LastModifiedDateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("lastmodifieddatetime_dt");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name_nvc");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("int")
                        .HasColumnName("schedule_id_i");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleId");

                    b.ToTable("t_explanation", (string)null);
                });

            modelBuilder.Entity("ScheduleAnywhere.Core.Domain.Filter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_i");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("active_b");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description_nvc");

                    b.Property<DateTime>("LastModifiedDateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("lastmodifieddatetime_dt");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name_nvc");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("int")
                        .HasColumnName("schedule_id_i");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleId");

                    b.ToTable("t_filter", (string)null);
                });

            modelBuilder.Entity("ScheduleAnywhere.Core.Domain.FilterDepartment", b =>
                {
                    b.Property<int>("FilterId")
                        .HasColumnType("int")
                        .HasColumnName("filter_id_i");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int")
                        .HasColumnName("department_id_i");

                    b.HasKey("FilterId", "DepartmentId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("t_mapFilterDepartment", (string)null);
                });

            modelBuilder.Entity("ScheduleAnywhere.Core.Domain.FilterEmployee", b =>
                {
                    b.Property<int>("FilterId")
                        .HasColumnType("int")
                        .HasColumnName("filter_id_i");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("employee_id_i");

                    b.HasKey("FilterId", "EmployeeId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("t_mapFilterEmployee", (string)null);
                });

            modelBuilder.Entity("ScheduleAnywhere.Core.Domain.FilterExplanation", b =>
                {
                    b.Property<int>("FilterId")
                        .HasColumnType("int")
                        .HasColumnName("filter_id_i");

                    b.Property<int>("ExplanationId")
                        .HasColumnType("int")
                        .HasColumnName("explanation_id_i");

                    b.HasKey("FilterId", "ExplanationId");

                    b.HasIndex("ExplanationId");

                    b.ToTable("t_mapFilterExplanation", (string)null);
                });

            modelBuilder.Entity("ScheduleAnywhere.Core.Domain.FilterLocation", b =>
                {
                    b.Property<int>("FilterId")
                        .HasColumnType("int")
                        .HasColumnName("filter_id_i");

                    b.Property<int>("LocationId")
                        .HasColumnType("int")
                        .HasColumnName("location_id_i");

                    b.HasKey("FilterId", "LocationId");

                    b.HasIndex("LocationId");

                    b.ToTable("t_mapFilterLocation", (string)null);
                });

            modelBuilder.Entity("ScheduleAnywhere.Core.Domain.FilterPosition", b =>
                {
                    b.Property<int>("FilterId")
                        .HasColumnType("int")
                        .HasColumnName("filter_id_i");

                    b.Property<int>("PositionId")
                        .HasColumnType("int")
                        .HasColumnName("position_id_i");

                    b.HasKey("FilterId", "PositionId");

                    b.HasIndex("PositionId");

                    b.ToTable("t_mapFilterPosition", (string)null);
                });

            modelBuilder.Entity("ScheduleAnywhere.Core.Domain.FilterShift", b =>
                {
                    b.Property<int>("FilterId")
                        .HasColumnType("int")
                        .HasColumnName("filter_id_i");

                    b.Property<int>("ShiftId")
                        .HasColumnType("int")
                        .HasColumnName("shift_id_i");

                    b.HasKey("FilterId", "ShiftId");

                    b.HasIndex("ShiftId");

                    b.ToTable("t_mapFilterShift", (string)null);
                });

            modelBuilder.Entity("ScheduleAnywhere.Core.Domain.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_i");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("active_b");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description_nvc");

                    b.Property<DateTime>("LastModifiedDateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("lastmodifieddatetime_dt");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name_nvc");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_id_i");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("t_location", (string)null);
                });

            modelBuilder.Entity("ScheduleAnywhere.Core.Domain.OpenShift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_i");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_dt");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("isactive_b");

                    b.Property<DateTime>("LastModifiedDateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("lastmodifieddatetime_dt");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("int")
                        .HasColumnName("schedule_id_i");

                    b.Property<int>("ShiftId")
                        .HasColumnType("int")
                        .HasColumnName("shift_id_i");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleId");

                    b.HasIndex("ShiftId");

                    b.ToTable("t_openShift", (string)null);
                });

            modelBuilder.Entity("ScheduleAnywhere.Core.Domain.OpenShiftRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_i");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("employee_id_i");

                    b.Property<bool?>("IsApproved")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("isapproved_b");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext")
                        .HasColumnName("notes_nvc");

                    b.Property<int>("OpenShiftId")
                        .HasColumnType("int")
                        .HasColumnName("openshift_id_i");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("requestedat_dt");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("reviewedat_dt");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("OpenShiftId");

                    b.ToTable("t_openShiftRequest", (string)null);
                });

            modelBuilder.Entity("ScheduleAnywhere.Core.Domain.Organization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_i");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("active_b");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("code_nvc");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_dt");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description_nvc");

                    b.Property<DateTime>("LastModifiedDateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("lastmodifieddatetime_dt");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name_nvc");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status_i");

                    b.HasKey("Id");

                    b.ToTable("t_organization", (string)null);
                });

            modelBuilder.Entity("ScheduleAnywhere.Core.Domain.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_i");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("active_b");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description_nvc");

                    b.Property<DateTime>("LastModifiedDateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("lastmodifieddatetime_dt");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name_nvc");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_id_i");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("t_position", (string)null);
                });

            modelBuilder.Entity("ScheduleAnywhere.Core.Domain.RequirementRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_i");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CoverageWatchId")
                        .HasColumnType("int")
                        .HasColumnName("coveragewatch_id_i");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int")
                        .HasColumnName("dayofweek_i");

                    b.Property<int>("MinimumCount")
                        .HasColumnType("int")
                        .HasColumnName("minimumcount_i");

                    b.HasKey("Id");

                    b.HasIndex("CoverageWatchId");

                    b.ToTable("t_requirementRow", (string)null);
                });

            modelBuilder.Entity("ScheduleAnywhere.Core.Domain.RoleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_i");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description_vc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name_vc");

                    b.HasKey("Id");

                    b.ToTable("t_role", (string)null);
                });

            modelBuilder.Entity("ScheduleAnywhere.Core.Domain.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_i");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("active_b");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description_nvc");

                    b.Property<bool>("IsPosted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("isposted_b");

                    b.Property<DateTime>("LastModifiedDateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("lastmodifieddatetime_dt");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name_nvc");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_id_i");

                    b.Property<DateTime?>("PostedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("posteddate_dt");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("t_schedule", (string)null);
                });

            modelBuilder.Entity("ScheduleAnywhere.Core.Domain.ScheduleItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_i");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_dt");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("employee_id_i");

                    b.Property<int?>("ExplanationId")
                        .HasColumnType("int")
                        .HasColumnName("explanation_id_i");

                    b.Property<DateTime>("LastModifiedDateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("lastmodifieddatetime_dt");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)")
                        .HasColumnName("notes_nvc");

                    b.Property<decimal?>("PaidHours")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("paidhours_m");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("int")
                        .HasColumnName("schedule_id_i");

                    b.Property<int?>("ShiftId")
                        .HasColumnType("int")
                        .HasColumnName("shift_id_i");

                    b.Property<decimal?>("UnpaidHours")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("unpaidhours_m");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ExplanationId");

                    b.HasIndex("ScheduleId");

                    b.HasIndex("ShiftId");

                    b.ToTable("t_scheduleItem", (string)null);
                });

            modelBuilder.Entity("ScheduleAnywhere.Core.Domain.Shift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_i");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("abbreviation_nvc");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("active_b");

                    b.Property<int>("BreakMinutes")
                        .HasColumnType("int")
                        .HasColumnName("breakminutes_i");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("code_nvc");

                    b.Property<int>("ColorId")
                        .HasColumnType("int")
                        .HasColumnName("color_id_i");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description_nvc");

                    b.Property<bool>("IsTimeOff")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("istimeoff_b");

                    b.Property<DateTime>("LastModifiedDateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("lastmodifieddatetime_dt");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name_nvc");

                    b.Property<decimal?>("PaidHours")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("paidhours_m");

                    b.Property<int?>("ParentShiftId")
                        .HasColumnType("int")
                        .HasColumnName("parentshift_id_i");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("int")
                        .HasColumnName("schedule_id_i");

                    b.Property<int?>("ShiftTagId")
                        .HasColumnType("int")
                        .HasColumnName("shifttag_id_i");

                    b.Property<int>("ShiftView")
                        .HasColumnType("int")
                        .HasColumnName("shiftview_i");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("starttime_dt");

                    b.Property<DateTime>("StopTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("stoptime_dt");

                    b.Property<int?>("TimeOffTagId")
                        .HasColumnType("int")
                        .HasColumnName("timeofftag_id_i");

                    b.Property<decimal?>("UnpaidHours")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("unpaidhours_m");

                    b.HasKey("Id");

                    b.HasIndex("ColorId");

                    b.HasIndex("ParentShiftId");

                    b.HasIndex("ScheduleId");

                    b.ToTable("t_shift", (string)null);
                });

            modelBuilder.Entity("ScheduleAnywhere.Core.Domain.ShiftColor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_i");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("HexCode")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("varchar(7)")
                        .HasColumnName("hexcode_nvc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name_nvc");

                    b.HasKey("Id");

                    b.ToTable("t_shiftColor", (string)null);
                });

            modelBuilder.Entity("ScheduleAnywhere.Core.Domain.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_i");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("active_b");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description_nvc");

                    b.Property<DateTime>("LastModifiedDateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("lastmodifieddatetime_dt");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name_nvc");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_id_i");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("t_skill", (string)null);
                });

            modelBuilder.Entity("ScheduleAnywhere.Core.Domain.SkillEmployee", b =>
                {
                    b.Property<int>("SkillId")
                        .HasColumnType("int")
                        .HasColumnName("skill_id_i");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("employee_id_i");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expirationdate_dt");

                    b.HasKey("SkillId", "EmployeeId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("t_mapSkillEmployee", (string)null);
                });

            modelBuilder.Entity("ScheduleAnywhere.Core.Domain.Workgroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_i");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("active_b");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description_nvc");

                    b.Property<DateTime>("LastModifiedDateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("lastmodifieddatetime_dt");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name_nvc");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("int")
                        .HasColumnName("schedule_id_i");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleId");

                    b.ToTable("t_workgroup", (string)null);
                });

            modelBuilder.Entity("ScheduleAnywhere.Core.Domain.WorkgroupDepartment", b =>
                {
                    b.Property<int>("WorkgroupId")
                        .HasColumnType("int")
                        .HasColumnName("workgroup_id_i");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int")
                        .HasColumnName("department_id_i");

                    b.HasKey("WorkgroupId", "DepartmentId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("t_mapWorkgroupDepartment", (string)null);
                });

            modelBuilder.Entity("ScheduleAnywhere.Core.Domain.WorkgroupEmployee", b =>
                {
                    b.Property<int>("WorkgroupId")
                        .HasColumnType("int")
                        .HasColumnName("workgroup_id_i");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("employee_id_i");

                    b.HasKey("WorkgroupId", "EmployeeId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("t_mapWorkgroupEmployee", (string)null);
                });

            modelBuilder.Entity("ScheduleAnywhere.Core.Domain.WorkgroupLocation", b =>
                {
                    b.Property<int>("WorkgroupId")
                        .HasColumnType("int")
                        .HasColumnName("workgroup_id_i");

                    b.Property<int>("LocationId")
                        .HasColumnType("int")
                        .HasColumnName("location_id_i");

                    b.HasKey("WorkgroupId", "LocationId");

                    b.HasIndex("LocationId");

                    b.ToTable("t_mapWorkgroupLocation", (string)null);
                });

            modelBuilder.Entity("ScheduleAnywhere.Core.Domain.WorkgroupPosition", b =>
                {
                    b.Property<int>("WorkgroupId")
                        .HasColumnType("int")
                        .HasColumnName("workgroup_id_i");

                    b.Property<int>("PositionId")
                        .HasColumnType("int")
                        .HasColumnName("position_id_i");

                    b.HasKey("WorkgroupId", "PositionId");

                    b.HasIndex("PositionId");

                    b.ToTable("t_mapWorkgroupPosition", (string)null);
                });

            modelBuilder.Entity("ScheduleAnywhere.Core.Domain.WorkgroupSkill", b =>
                {
                    b.Property<int>("WorkgroupId")
                        .HasColumnType("int")
                        .HasColumnName("workgroup_id_i");

                    b.Property<int>("SkillId")
                        .HasColumnType("int")
                        .HasColumnName("skill_id_i");

                    b.HasKey("WorkgroupId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("t_mapWorkgroupSkill", (string)null);
                });

            modelBuilder.Entity("ScheduleAnywhere.Core.Domain.CoverageWatch", b =>
                {
                    b.HasOne("ScheduleAnywhere.Core.Domain.Schedule", "Schedule")
                        .WithMany("CoverageWatches")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("ScheduleAnywhere.Core.Domain.CoverageWatchDepartment", b =>
                {
                    b.HasOne("ScheduleAnywhere.Core.Domain.CoverageWatch", "CoverageWatch")
                        .WithMany("Departments")
                        .HasForeignKey("CoverageWatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScheduleAnywhere.Core.Domain.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CoverageWatch");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("ScheduleAnywhere.Core.Domain.CoverageWatchPosition", b =>
                {
                    b.HasOne("ScheduleAnywhere.Core.Domain.CoverageWatch", "CoverageWatch")
                        .WithMany("Positions")
                        .HasForeignKey("CoverageWatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScheduleAnywhere.Core.Domain.Position", "Position")
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CoverageWatch");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("ScheduleAnywhere.Core.Domain.CoverageWatchShift", b =>
                {
                    b.HasOne("ScheduleAnywhere.Core.Domain.CoverageWatch", "CoverageWatch")
                        .WithMany("Shifts")
                        .HasForeignKey("CoverageWatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScheduleAnywhere.Core.Domain.Shift", "Shift")
                        .WithMany()
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CoverageWatch");

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("ScheduleAnywhere.Core.Domain.Department", b =>
                {
                    b.HasOne("ScheduleAnywhere.Core.Domain.Organization", "Organization")
                        .WithMany("Departments")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("ScheduleAnywhere.Core.Domain.Employee", b =>
                {
                    b.HasOne("ScheduleAnywhere.Core.Domain.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScheduleAnywhere.Core.Domain.Location", "Location")
                        .WithMany("Employees")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScheduleAnywhere.Core.Domain.Organization", "Organization")
                        .WithMany("Employees")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScheduleAnywhere.Core.Domain.Position", "Position")
                        .WithMany("Employees")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScheduleAnywhere.Core.Domain.Employee", "Supervisor")
                        .WithMany("DirectReports")
                        .HasForeignKey("SupervisorEmployeeId");

                    b.Navigation("Department");

                    b.Navigation("Location");

                    b.Navigation("Organization");

                    b.Navigation("Position");

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("ScheduleAnywhere.Core.Domain.EmployeeRole", b =>
                {
                    b.HasOne("ScheduleAnywhere.Core.Domain.Employee", "Employee")
                        .WithMany("EmployeeRoles")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScheduleAnywhere.Core.Domain.RoleEntity", "RoleEntity")
                        .WithMany("EmployeeRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("RoleEntity");
                });

            modelBuilder.Entity("ScheduleAnywhere.Core.Domain.EmployeeScheduleAccess", b =>
                {
                    b.HasOne("ScheduleAnywhere.Core.Domain.Employee", "Employee")
                        .WithMany("ScheduleAccesses")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScheduleAnywhere.Core.Domain.Schedule", "Schedule")
                        .WithMany("EmployeeAccesses")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("ScheduleAnywhere.Core.Domain.Explanation", b =>
                {
                    b.HasOne("ScheduleAnywhere.Core.Domain.Schedule", "Schedule")
                        .WithMany("Explanations")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("ScheduleAnywhere.Core.Domain.Filter", b =>
                {
                    b.HasOne("ScheduleAnywhere.Core.Domain.Schedule", "Schedule")
                        .WithMany("Filters")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("ScheduleAnywhere.Core.Domain.FilterDepartment", b =>
                {
                    b.HasOne("ScheduleAnywhere.Core.Domain.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScheduleAnywhere.Core.Domain.Filter", "Filter")
                        .WithMany("Departments")
                        .HasForeignKey("FilterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Filter");
                });

            modelBuilder.Entity("ScheduleAnywhere.Core.Domain.FilterEmployee", b =>
                {
                    b.HasOne("ScheduleAnywhere.Core.Domain.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScheduleAnywhere.Core.Domain.Filter", "Filter")
                        .WithMany("Employees")
                        .HasForeignKey("FilterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Filter");
                });

            modelBuilder.Entity("ScheduleAnywhere.Core.Domain.FilterExplanation", b =>
                {
                    b.HasOne("ScheduleAnywhere.Core.Domain.Explanation", "Explanation")
                        .WithMany()
                        .HasForeignKey("ExplanationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScheduleAnywhere.Core.Domain.Filter", "Filter")
                        .WithMany("Explanations")
                        .HasForeignKey("FilterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Explanation");

                    b.Navigation("Filter");
                });

            modelBuilder.Entity("ScheduleAnywhere.Core.Domain.FilterLocation", b =>
                {
                    b.HasOne("ScheduleAnywhere.Core.Domain.Filter", "Filter")
                        .WithMany("Locations")
                        .HasForeignKey("FilterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScheduleAnywhere.Core.Domain.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Filter");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("ScheduleAnywhere.Core.Domain.FilterPosition", b =>
                {
                    b.HasOne("ScheduleAnywhere.Core.Domain.Filter", "Filter")
                        .WithMany("Positions")
                        .HasForeignKey("FilterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScheduleAnywhere.Core.Domain.Position", "Position")
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Filter");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("ScheduleAnywhere.Core.Domain.FilterShift", b =>
                {
                    b.HasOne("ScheduleAnywhere.Core.Domain.Filter", "Filter")
                        .WithMany("Shifts")
                        .HasForeignKey("FilterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScheduleAnywhere.Core.Domain.Shift", "Shift")
                        .WithMany()
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Filter");

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("ScheduleAnywhere.Core.Domain.Location", b =>
                {
                    b.HasOne("ScheduleAnywhere.Core.Domain.Organization", "Organization")
                        .WithMany("Locations")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("ScheduleAnywhere.Core.Domain.OpenShift", b =>
                {
                    b.HasOne("ScheduleAnywhere.Core.Domain.Schedule", "Schedule")
                        .WithMany("OpenShifts")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScheduleAnywhere.Core.Domain.Shift", "Shift")
                        .WithMany()
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Schedule");

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("ScheduleAnywhere.Core.Domain.OpenShiftRequest", b =>
                {
                    b.HasOne("ScheduleAnywhere.Core.Domain.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScheduleAnywhere.Core.Domain.OpenShift", "OpenShift")
                        .WithMany("Requests")
                        .HasForeignKey("OpenShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("OpenShift");
                });

            modelBuilder.Entity("ScheduleAnywhere.Core.Domain.Position", b =>
                {
                    b.HasOne("ScheduleAnywhere.Core.Domain.Organization", "Organization")
                        .WithMany("Positions")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("ScheduleAnywhere.Core.Domain.RequirementRow", b =>
                {
                    b.HasOne("ScheduleAnywhere.Core.Domain.CoverageWatch", "CoverageWatch")
                        .WithMany("RequirementRows")
                        .HasForeignKey("CoverageWatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CoverageWatch");
                });

            modelBuilder.Entity("ScheduleAnywhere.Core.Domain.Schedule", b =>
                {
                    b.HasOne("ScheduleAnywhere.Core.Domain.Organization", "Organization")
                        .WithMany("Schedules")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("ScheduleAnywhere.Core.Domain.ScheduleItem", b =>
                {
                    b.HasOne("ScheduleAnywhere.Core.Domain.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScheduleAnywhere.Core.Domain.Explanation", "Explanation")
                        .WithMany()
                        .HasForeignKey("ExplanationId");

                    b.HasOne("ScheduleAnywhere.Core.Domain.Schedule", "Schedule")
                        .WithMany("ScheduleItems")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScheduleAnywhere.Core.Domain.Shift", "Shift")
                        .WithMany()
                        .HasForeignKey("ShiftId");

                    b.Navigation("Employee");

                    b.Navigation("Explanation");

                    b.Navigation("Schedule");

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("ScheduleAnywhere.Core.Domain.Shift", b =>
                {
                    b.HasOne("ScheduleAnywhere.Core.Domain.ShiftColor", "Color")
                        .WithMany()
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScheduleAnywhere.Core.Domain.Shift", "ParentShift")
                        .WithMany("ChildShifts")
                        .HasForeignKey("ParentShiftId");

                    b.HasOne("ScheduleAnywhere.Core.Domain.Schedule", "Schedule")
                        .WithMany("Shifts")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Color");

                    b.Navigation("ParentShift");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("ScheduleAnywhere.Core.Domain.Skill", b =>
                {
                    b.HasOne("ScheduleAnywhere.Core.Domain.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("ScheduleAnywhere.Core.Domain.SkillEmployee", b =>
                {
                    b.HasOne("ScheduleAnywhere.Core.Domain.Employee", "Employee")
                        .WithMany("Skills")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScheduleAnywhere.Core.Domain.Skill", "Skill")
                        .WithMany("SkillEmployees")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("ScheduleAnywhere.Core.Domain.Workgroup", b =>
                {
                    b.HasOne("ScheduleAnywhere.Core.Domain.Schedule", "Schedule")
                        .WithMany("Workgroups")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("ScheduleAnywhere.Core.Domain.WorkgroupDepartment", b =>
                {
                    b.HasOne("ScheduleAnywhere.Core.Domain.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScheduleAnywhere.Core.Domain.Workgroup", "Workgroup")
                        .WithMany("Departments")
                        .HasForeignKey("WorkgroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Workgroup");
                });

            modelBuilder.Entity("ScheduleAnywhere.Core.Domain.WorkgroupEmployee", b =>
                {
                    b.HasOne("ScheduleAnywhere.Core.Domain.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScheduleAnywhere.Core.Domain.Workgroup", "Workgroup")
                        .WithMany("Employees")
                        .HasForeignKey("WorkgroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Workgroup");
                });

            modelBuilder.Entity("ScheduleAnywhere.Core.Domain.WorkgroupLocation", b =>
                {
                    b.HasOne("ScheduleAnywhere.Core.Domain.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScheduleAnywhere.Core.Domain.Workgroup", "Workgroup")
                        .WithMany("Locations")
                        .HasForeignKey("WorkgroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Workgroup");
                });

            modelBuilder.Entity("ScheduleAnywhere.Core.Domain.WorkgroupPosition", b =>
                {
                    b.HasOne("ScheduleAnywhere.Core.Domain.Position", "Position")
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScheduleAnywhere.Core.Domain.Workgroup", "Workgroup")
                        .WithMany("Positions")
                        .HasForeignKey("WorkgroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Position");

                    b.Navigation("Workgroup");
                });

            modelBuilder.Entity("ScheduleAnywhere.Core.Domain.WorkgroupSkill", b =>
                {
                    b.HasOne("ScheduleAnywhere.Core.Domain.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScheduleAnywhere.Core.Domain.Workgroup", "Workgroup")
                        .WithMany("Skills")
                        .HasForeignKey("WorkgroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");

                    b.Navigation("Workgroup");
                });

            modelBuilder.Entity("ScheduleAnywhere.Core.Domain.CoverageWatch", b =>
                {
                    b.Navigation("Departments");

                    b.Navigation("Positions");

                    b.Navigation("RequirementRows");

                    b.Navigation("Shifts");
                });

            modelBuilder.Entity("ScheduleAnywhere.Core.Domain.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("ScheduleAnywhere.Core.Domain.Employee", b =>
                {
                    b.Navigation("DirectReports");

                    b.Navigation("EmployeeRoles");

                    b.Navigation("ScheduleAccesses");

                    b.Navigation("Skills");
                });

            modelBuilder.Entity("ScheduleAnywhere.Core.Domain.Filter", b =>
                {
                    b.Navigation("Departments");

                    b.Navigation("Employees");

                    b.Navigation("Explanations");

                    b.Navigation("Locations");

                    b.Navigation("Positions");

                    b.Navigation("Shifts");
                });

            modelBuilder.Entity("ScheduleAnywhere.Core.Domain.Location", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("ScheduleAnywhere.Core.Domain.OpenShift", b =>
                {
                    b.Navigation("Requests");
                });

            modelBuilder.Entity("ScheduleAnywhere.Core.Domain.Organization", b =>
                {
                    b.Navigation("Departments");

                    b.Navigation("Employees");

                    b.Navigation("Locations");

                    b.Navigation("Positions");

                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("ScheduleAnywhere.Core.Domain.Position", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("ScheduleAnywhere.Core.Domain.RoleEntity", b =>
                {
                    b.Navigation("EmployeeRoles");
                });

            modelBuilder.Entity("ScheduleAnywhere.Core.Domain.Schedule", b =>
                {
                    b.Navigation("CoverageWatches");

                    b.Navigation("EmployeeAccesses");

                    b.Navigation("Explanations");

                    b.Navigation("Filters");

                    b.Navigation("OpenShifts");

                    b.Navigation("ScheduleItems");

                    b.Navigation("Shifts");

                    b.Navigation("Workgroups");
                });

            modelBuilder.Entity("ScheduleAnywhere.Core.Domain.Shift", b =>
                {
                    b.Navigation("ChildShifts");
                });

            modelBuilder.Entity("ScheduleAnywhere.Core.Domain.Skill", b =>
                {
                    b.Navigation("SkillEmployees");
                });

            modelBuilder.Entity("ScheduleAnywhere.Core.Domain.Workgroup", b =>
                {
                    b.Navigation("Departments");

                    b.Navigation("Employees");

                    b.Navigation("Locations");

                    b.Navigation("Positions");

                    b.Navigation("Skills");
                });
#pragma warning restore 612, 618
        }
    }
}
